name: Build Backend and Frontend
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Backend - Install & Build
        run: |
          cd findex
          npm install
          npm run build

      - name: Frontend - Install & Build
        run: |
          cd findex-frontend
          npm install
          npm run build

# name: Deploy Findex Backend

# on:
#   push:
#     branches: ['main']
#     paths:
#       - 'findex/**'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Login Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USER }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build & Push Backend Image
#         uses: docker/build-push-action@v5
#         with:
#           context: ./findex
#           push: true
#           tags: ${{ secrets.DOCKER_USER }}/findex-backend:latest

#       - name: Deploy on Render
#         run: |
#           curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}
